# Generated by Django 5.0.6 on 2024-06-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_remove_category_tasks"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="categories",
            field=models.ManyToManyField(to="categories.category"),
        ),
    ]
